version: '3'
services:
  klipper-stats:
    container_name: klipper-stats
    build: ../klipper-stats
    ports:
      - '3030:3030'
    environment:
      - PORT=3030
      - KLIPPER_HOST=127.0.0.1
    restart: on-failure
    network_mode: host
