{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "smoothing",
    "query": "5s,10s,15s,30s,1m,2m,5m,10m,15m,30m"
   },
   { "name": "network_interfaces", "query": { "query": "node_network_info" } },
   { "name": "MCUs", "query": { "query": "moonraker_mcu_info" } },
   { "name": "DifferenceTemps", "query": { "query": "moonraker_temp_target" } }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(mode) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_thermal_zone_temp", "legendFormat": "{{type}} {{zone}}" }
   ]
  },
  {
   "title": "Host Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1" },
    { "expr": "node_load5", "legendFormat": "load 5" },
    { "expr": "node_load15", "legendFormat": "load 15" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "Allocated"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "title": "Network ($network_interfaces)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "repeat": "network_interfaces",
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"$network_interfaces\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"$network_interfaces\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Klipper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Heater Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(moonraker_temp_power[$smoothing])",
     "legendFormat": "{{name}} Power"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(moonraker_temp_temperature[$smoothing])",
     "legendFormat": "{{name}} Actual"
    },
    {
     "expr": "avg_over_time(moonraker_temp_target[$smoothing])",
     "legendFormat": "{{name}} Target"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "moonraker_fan_speed", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Differences",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "downsampler": "mean",
     "expression": "round(($ACTUAL - $TARGET) * 10) / 10\n",
     "type": "math",
     "upsampler": "fillna"
    }
   ]
  },
  { "title": "MCU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "MCUs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "moonraker_mcu_info{name=~\"$MCUs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Freq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_freq{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Awake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_mcu_awake{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Bytes Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(name) (rate(moonraker_mcu_stats_bytes_read{name=~\"$MCUs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Bytes Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(name) (rate(moonraker_mcu_stats_bytes_write{name=~\"$MCUs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Bytes Retransmit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_bytes_retransmit{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Ready Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_ready_bytes{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Receive Seq Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (rate(moonraker_mcu_stats_receive_seq{name=~\"$MCUs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Send Seq Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (rate(moonraker_mcu_stats_send_seq{name=~\"$MCUs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Retransmit Seq",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_retransmit_seq{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Bytes Invalid",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_bytes_invalid{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MCU Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "MCU SRTT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_srtt{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU RTO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_rto{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Task Avg",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_mcu_task_avg{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU RTTVAR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_rttvar{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Stalled Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_stalled_bytes{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCU Task StdDev",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(name) (moonraker_mcu_stats_mcu_task_stddev{name=~\"$MCUs\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}